### ISSUE TITLE
style test fails

### ISSUE THREAD

**Issue by vmora** [Oslandia/SFCGAL#90] opened 2015-06-16 15:33 UTC

**Comment by vmora** [comment] 2015-06-16 15:34
@strl following what you said in #83 "a propos" astyle output depending on version.

I'd like to find a robust way to check style, do you know any ?

**Comment by strk** [comment] 2015-06-17 14:12
Duplicate of #78 ?

**Comment by mhugo** [comment] 2015-09-18 15:31
Style tests are now disabled

**Closed by mhugo** 2015-09-18 15:31 UTC
